name: Build with Mill

on:
  workflow_call:
    inputs:
      preparecmd:
        default: ''
        type: string
      buildcmd:
        default: ''
        type: string
      millargs:
        default: ''
        type: string
      java-version:
        required: true
        type: string
      os:
        default: 'ubuntu-latest'
        type: string
      continue-on-error:
        default: false
        type: boolean

jobs:
  build:

    runs-on: ${{ inputs.os }}
    continue-on-error: ${{ inputs.continue-on-error }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin

      - name: Prepare run '${{ inputs.buildcmd }}'
        run: ${{ inputs.preparecmd }}
        if: inputs.preparecmd != ''

      - name: Run '${{ inputs.buildcmd }}'
        run: ${{ inputs.buildcmd }}
        if: inputs.buildcmd != ''

      - name: Run Mill '${{ inputs.millargs }}'
        run:  ./mill -i -k ${{ inputs.millargs }}
        if: inputs.millargs != '' && !startsWith(inputs.os, 'windows')

      - name: Run Mill (on Windows) '${{ inputs.millargs }}'
        run: cmd /C %GITHUB_WORKSPACE%\ci\mill.bat -i -d -k ${{ inputs.millargs }}
        if: inputs.millargs != '' && startsWith(inputs.os, 'windows')
